# Title shown in Application Information tab.
title: Palo Alto Networks Prisma Access ZTNA Connector Application - BYOL
# Sub Title shown in Application Information tab.
description: Private Application Access for Prisma Access via ZTNA Connector- BYOL
schemaVersion: 1.1.0
version: "20190304"

# URL of Logo Icon used on Application Information tab. You can copy the contentId from the Marketplace listing logo URL in the Marketplace Partner portal.
# (Optional)
logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=71617800

# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the
# "marketplace-listing-id" tag for the same purpose.
source:
  type: marketplace
  reference: 12345

locale: "en"
variableGroups:
  - title: "Hidden Variable Group"
    visible: false
    variables:
#"variables used internally - not exposed to end user"
      - tenancy_ocid
      - region
      - mp_listing_id
      - mp_listing_resource_id
      - mp_listing_resource_version
      - availability_domain_number
      - mp_subscription_enabled
      #change compute.tf and move custom_image_id to Compute group in case you want to use a custom_image
      - custom_image_id
      - marketplace_source_images
      - compartment_ocid
      - tag_key_name
      - tag_value
      - vm_compute_shape

  - title: "Compute Configuration"
    variables:
      - compute_compartment_ocid
      - vm_display_name
      - availability_domain_name


  - title: "Virtual Cloud Network and Subnet"
    variables:
      - network_compartment_ocid
      - vcn_id
      - number_of_nics
      - internet_subnet_id
      - data_center_subnet_id

  - title: "ZTNA Connector License"
    variables:
      - vm_license_key
      - vm_license_secret

#  - title: "Additional Configuration Options"
#    variables:
#      - tag_key_name
#      - tag_value


######################################################
##############          VARIABLES        #############
######################################################

variables:
  # Hidden variables

######################################################
##############    HIDDEN VARIABLES       #############
######################################################


  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true

  availability_domain_number:
    type: string
    required: false
    description: Availability Domain Number (Not used)

######################################################
##############   MARKETPLACE VARIABLES   #############
######################################################

  mp_listing_id:
    type: string
    required: true
    description: Marketplace Listing ID

  mp_listing_resource_id:
    type: oci:core:image:id
    required: true
    description: Marketplace Image OCID
    dependsOn:
      compartmentId: compute_compartment_ocid

  mp_listing_resource_version:
    type: string
    required: true
    description: Marketplace Listing package version


  mp_subscription_enabled:
    type: boolean
    title: Use Marketplace Image?
    default: false

  custom_image_id:
    type: string
    required: true
    title: Custom Image OCID
    visible:
      eq:
        - mp_subscription_enabled
        - false


  tag_key_name:
    type: string
    required: true
    title: Tag key name

  tag_value:
    type: string
    required: true
    title: Tag value


######################################################
##############    COMPUTE VARIABLES      #############
######################################################

  compute_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compute Compartment
    description: The compartment in which to create all Compute resources
    default: compartment_ocid

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: compute_compartment_ocid
    required: true
    default: 1
    title: Availability Domain
    description: Availability Domain

  vm_display_name:
    type: string
    required: true
    title: Instance Name
    description: The name of the Instance


######################################################
##############     NETWORK VARIABLES     #############
######################################################

  network_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Network Compartment
    description: The compartment in which to create all Network resources
    default: compartment_ocid


######## VCN ########
  vcn_id:
    type: oci:core:vcn:id
    dependsOn:
      compartmentId: network_compartment_ocid
    required: true
    title: Existing VCN
    description: An existing Virtual Cloud Network (VCN) in which to create the compute instance.

######## Choose between a 1-arm and a 2-arm connector ########
  number_of_nics:
    type: enum
    title: "Specify the Number of Network Interfaces"
    description: "Choose between a one-armed or a two-armed ZTNA Connector Deployment."
    required: true
    enum:
      - "1"
      - "2"
    default: "1"

######## INTERNET SUBNET ########
  internet_subnet_id:
    type: oci:core:subnet:id
    dependsOn:
      vcnId: vcn_id
      compartmentId: network_compartment_ocid
    default: ''
    required: true
    title: Internet Subnet
    description: An existing subnet facing the Internet present in the chosen VCN for NIC #1.

######## DATA CENTER SUBNET ########
  data_center_subnet_id:
    type: oci:core:subnet:id
    dependsOn:
      vcnId: vcn_id
      compartmentId: network_compartment_ocid
    default: ''
    required: false
    title: Data Center Subnet
    description: An existing subnet facing the Data Center Applications present in the chosen VCN for NIC #2.
    visible:
      eq:
        - number_of_nics
        - "2"


######################################################
#############     ZTNA LICENSE VARIABLES     #########
######################################################

  vm_license_key:
    type: string
    required: true
    title: ZTNA Connector License Key

  vm_license_secret:
    type: string
    required: true
    title: ZTNA Connector License Secret

#############################################
###########    OUTPUT GROUPS     ############
#############################################

outputGroups:
  - title: "Instance Management"
    outputs:
      - instance_private_ip


#############################################
##############     OUTPUTS     ##############
#############################################

outputs:
  instance_private_ip:
    type: link
    title: Private IP
    visible: true

primaryOutputButton: instance_https_url
