AWSTemplateFormatVersion: '2010-09-09'
Description: 'Prisma Access ZTNA Connector Deployment, use this template for 1-ARM
  deployments only. Version: 4.0 Date: 02-28-2023 Contact:  https://www.paloaltonetworks.com/company/contact-support '
Parameters:
  InstanceName:
    Description: ZTNA Connector EC2 Instance Name
    Type: String
  IONKey:
    Description: ZTNA Connector Key
    Type: String
  IONSecret:
    Description: ZTNA Connector Secret
    Type: String
    NoEcho: true
  MyVPC:
    Description: VPC to operate in
    Type: AWS::EC2::VPC::Id
  PrivateSubnet:
    Description: Subnet for Private port
    Type: AWS::EC2::Subnet::Id
  DCLanIP:
    Description: Optionally specify a static IP for Single port, 0.0.0.0 = DHCP
    Type: String
    MinLength: '7'
    MaxLength: '15'
    Default: 0.0.0.0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
    ConstraintDescription: must be a valid IPv4 address in the form x.x.x.x
  CgnxHostName:
    Description: Cgnx controller hostname
    Type: String
  CgnxHostIp:
    Description: Cgnx controller ip
    Type: String
Conditions:
  StaticDCLanIP: !Not [!Equals [!Ref 'DCLanIP', 0.0.0.0]]
Mappings:
  RegionMap:
    us-east-1:
      ION: ami-00e3207f06a990ba3
    us-east-2:
      ION: ami-0bca3b2082c49b194
    us-west-1:
      ION: ami-02390f9fd2d045a1b
    us-west-2:
      ION: ami-01d91a637f4bc4969
    ca-central-1:
      ION: ami-0dd1740b439281202
    sa-east-1:
      ION: ami-0fa221b8ba80c7baa
    eu-central-1:
      ION: ami-09f94c207e98a626a
    eu-west-1:
      ION: ami-09cb7ea30b7b38400
    eu-west-2:
      ION: ami-090618c1ccd33fe90
    ap-south-1:
      ION: ami-0e1e75fc6d1da97ba
    ap-northeast-1:
      ION: ami-0cc387e84557191d7
    ap-northeast-2:
      ION: ami-0e432149c9c650eb5
    ap-southeast-1:
      ION: ami-003f579b3387aac99
    ap-southeast-2:
      ION: ami-08704542e023ece88
    eu-central-2:
      ION: ami-093f497e5f1ce2e21
    eu-west-3:
      ION: ami-094893e0c32497a19
    eu-north-1:
      ION: ami-0bb7e73ab39f1a2b4
    eu-south-1:
      ION: ami-0547ea15020f50d64
    eu-south-2:
      ION: ami-063c68d6524fa10c0
    ap-southeast-3:
      ION: ami-091357637502e0433
    ap-southeast-4:
      ION: ami-05e3d20651cafe234
    ap-south-2:
      ION: ami-0fbce0f11f8c92099
    ap-northeast-3:
      ION: ami-0533d386ee75d88af
    ap-east-1:
      ION: ami-0d40574c464be02a3
    me-central-1:
      ION: ami-0c6b3f1eb053783cd
    me-south-1:
      ION: ami-00cf5b4ebedfc1495
    af-south-1:
      ION: ami-077c1be57810319db
  InstanceMap:
    ion200v:
      instanceType: m5.xlarge
  ModelMap:
    ion200v:
      model: ion 200v
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [InstanceMap, ion200v, instanceType]
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', ION]
      NetworkInterfaces:
      - NetworkInterfaceId: !Ref 'DCLanIface'
        DeviceIndex: 0
      UserData: !Base64
        Fn::Sub:
        - "General:\n  model: ${LocalModelMap}\n\  host1_name: ${CgnxHostName}\n  host1_ip:  ${CgnxHostIp}\n\nLicense:\n  key: ${IONKey}\n  secret:\
          \ ${IONSecret}\n\n1:\n  role: PublicWAN\n  type: DHCP\n"
        - LocalModelMap: !FindInMap [ModelMap, ion200v, model]
      Tags:
      - Key: Name
        Value: !Ref 'InstanceName'
  DCLanIface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      PrivateIpAddress: !If [StaticDCLanIP, !Ref 'DCLanIP', !Ref 'AWS::NoValue']
      SubnetId: !Ref 'PrivateSubnet'
      Description: Interface for single port
      GroupSet:
      - !Ref 'ZTNASG'
      SourceDestCheck: false
      Tags:
      - Key: Network
        Value: DCLan
  ZTNASG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${AWS::StackName}-security-group'
      GroupDescription: ZTNA Connector Allow Egress SG
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0
      VpcId: !Ref 'MyVPC'
      Tags:
      - Key: Name
        Value: !Join [' ', [!Ref 'InstanceName', Public Security Group]]
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required Network Configuration
      Parameters:
      - MyVPC
      - PrivateSubnet
    - Label:
        default: Required ZTNA Connector Details
      Parameters:
      - InstanceName
      - IONKey
      - IONSecret
    - Label:
        default: Optional Network Configuration
      Parameters:
      - DCLanIP
      - CgnxHostName
      - CgnxHostIp
    ParameterLabels:
      MyVPC:
        default: Which VPC should ZTNA Connector be deployed to?
      PrivateSubnet:
        default: Specify the subnet for the single port
      DCLanIP:
        default: Single Port Static IP
      CgnxHostName:
        default: Hostname of cgnx controller
      CgnxHostIp:
        default: Ip of cgnx controller
      IONKey:
        default: Provide the ZTNA Connector License Key
      IONSecret:
        default: Provide the ZTNA Connector License Secret
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'MyEC2Instance'
  IONModel:
    Description: ION model selected
    Value: !FindInMap [ModelMap, ion200v, model]
