project_id            = "my-gcp-project"
vm_name               = "my-ztna-connector"
vm_internet_subnet    = "nat-gateway-to-internet"
vm_data_center_subnet = "data-center-subnet"
vm_license_key        = "<LICENSE-KEY>"
vm_license_secret     = "<LICENSE-SECRET>"
